In [49]:
import pandas as pd
import numpy as np

# **Brakujące wartości**

**Brakujące wartości** to rekordy, które są nieobecne w zestawie danych.

**Przyczyny występowania**:
* Błąd człowieka podczas wprowadzania danych​

* Ochrona prywatności (dane wrażliwe)
* Brak odpowiedzi w ankietach

Problemy techniczne przy zbieraniu danych

Jest to jeden z **najczęściej występujących problemów** w analizie danych i kluczowy etap wstępnego przetwarzania (data preprocessing).

In [50]:
# Definicja DataFrame
df_student = pd.DataFrame({
    'imie': ['Anna', 'Piotr', 'Maria', 'Jan', 'Katarzyna', 'Tomasz', 'Magdalena', 'Paweł', 'Ewa', 'Michał'],
    'wiek': [20, 22, 21, np.nan, 23, 20, 22, np.nan, 21, 23],
    'ocena_matematyka': [4.5, np.nan, 5.0, 4.0, 3.5, 4.5, 5.0, 3.5, np.nan, 4.0],
    'ocena_fizyka': [5.0, 4.5, np.nan, 4.0, 4.5, np.nan, 5.0, 4.0, 4.5, np.nan],
    'ocena_informatyka': [4.0, 3.5, 4.5, np.nan, 5.0, 3.5, 4.5, 4.0, np.nan, 4.5],
    'miasto': ['Warszawa', 'Kraków', 'Wrocław', 'Poznań', 'Gdańsk', np.nan, 'Warszawa', 'Kraków', 'Wrocław', 'Poznań']
})

In [51]:
# 1. Sprawdzenie czy są brakujące wartości
print("1. Sprawdzenie brakujących wartości (True = brak):")
print(df_student.isnull())
# lub: df.isna()
print("\n" + "="*60 + "\n")

1. Sprawdzenie brakujących wartości (True = brak):
    imie   wiek  ocena_matematyka  ocena_fizyka  ocena_informatyka  miasto
0  False  False             False         False              False   False
1  False  False              True         False              False   False
2  False  False             False          True              False   False
3  False   True             False         False               True   False
4  False  False             False         False              False   False
5  False  False             False          True              False    True
6  False  False             False         False              False   False
7  False   True             False         False              False   False
8  False  False              True         False               True   False
9  False  False             False          True              False   False

============================================================

In [52]:
# 2. Liczba brakujących wartości w każdej kolumnie
print("2. Liczba brakujących wartości w każdej kolumnie:")
print(df_student.isna().sum())
print("\n" + "="*60 + "\n")

2. Liczba brakujących wartości w każdej kolumnie:
imie                 0
wiek                 2
ocena_matematyka     2
ocena_fizyka         3
ocena_informatyka    2
miasto               1
dtype: int64

============================================================

In [53]:
# 3. Procent brakujących wartości
print("3. Procent brakujących wartości w każdej kolumnie:")
print((df_student.isnull().sum() / len(df_student)) * 100)
print("\n" + "="*60 + "\n")

3. Procent brakujących wartości w każdej kolumnie:
imie                  0.0
wiek                 20.0
ocena_matematyka     20.0
ocena_fizyka         30.0
ocena_informatyka    20.0
miasto               10.0
dtype: float64

============================================================

In [54]:
# 4. Całkowita liczba brakujących wartości
print("4. Całkowita liczba brakujących wartości w całym DataFrame:")
print(df_student.isnull().sum().sum())

4. Całkowita liczba brakujących wartości w całym DataFrame:
10

## **Rozwiązanie kwestii brakujących danych**

* **Usuwanie rekordów** zawierających brakujące wartości.
* **Ręczne uzupełnianie** brakujących wartości.
* Uzupełnianie **brakujących wartości wskaźnikami** tendencji centralnej, np.: średnią, medianą czy dominantą.
  * **Średniej** używamy w przypadku cech numerycznych,
  * **mediany** w cechach porządkowych,
  * **dominantę** (czyli najczęściej powtarzającą się wartość) umieszczamy w cechach kategorialnych.

Uzupełnianie **najbardziej prawdopodobną wartością** przy użyciu modeli uczenia maszynowego, takich jak regresja, drzewa decyzyjne czy algorytm KNN.

## **Czym jest NaN i dlaczego jest wyjątkowy?**

**NaN** (Not a Number) – specjalna wartość reprezentująca brakujące dane.

Dane mogą zawierać różne oznaczenia braków:
* Tekstowe: "NA", "N/A", "brak", "?", "-"

* Numeryczne: 0, -999, -1​

* Inne: puste stringi ""

In [55]:
df = pd.DataFrame({
    'A': [1, np.nan, 3],# ✓ NaN - brakująca wartość ​
    'B': [4, None, 6],  # ✓ None - też brakująca ​
    'C': [7, 0, 9],     # ✗ 0 - NIE jest brakująca! ​
    'D': ['x', '', 'z'] # ✗ '' - NIE jest brakująca! ​
})

In [56]:
df.isnull().sum()

A    1
B    1
C    0
D    0
dtype: int64

## **Usuwanie brakujących wartości**

Usuń wiersze z DOWOLNĄ brakującą wartością (domyślnie) ​

```
df.dropna()
df.dropna(how='any')
```

Usuń wiersze tylko gdy WSZYSTKIE wartości są brakujące df.dropna(how='all')
```
df.dropna(how="all")
```

Usuń kolumny z brakującymi wartościami
```
df.dropna(axis=1)
```

## **Uzupełnienie średnią lub modą​**

W pandas *dataFrame* możemy uzupełnić brakujące wartości za pomocą funkcji `fillna()`.
* Przyjmuje ona jedną wartość, która będzie wstawiana w pustych pozycjach lub zamiast wartości NaN.

Uzupełnia wszystkie brakujące wartości w kolumnie age średnią obliczoną z tejże kolumny

```data['age'] = data.age.fillna(data.age.mean())​```

Uzupełnia wszystkie brakujące wartości w kolumnie income medianą obliczoną z tejże kolumny

```data['income']=data.income.fillna(data.income.median())```

Zastępuje wszystkie brakujące wartości w kolumnie gender (kolumna kategorii) dominantą wyliczoną z tejże kolumny​

```data['gender']=data['gender'].fillna(data['gender'].mode()[0])​```

In [57]:
df_student["wiek"] = df_student.wiek.fillna(df_student.wiek.mean())
df_student

,imie,wiek,ocena_matematyka,ocena_fizyka,ocena_informatyka,miasto
0,Anna,20.0,4.5,5.0,4.0,Warszawa
1,Piotr,22.0,NaN,4.5,3.5,Kraków
2,Maria,21.0,5.0,NaN,4.5,Wrocław
3,Jan,21.5,4.0,4.0,NaN,Poznań
4,Katarzyna,23.0,3.5,4.5,5.0,Gdańsk
5,Tomasz,20.0,4.5,NaN,3.5,NaN
6,Magdalena,22.0,5.0,5.0,4.5,Warszawa
7,Paweł,21.5,3.5,4.0,4.0,Kraków
8,Ewa,21.0,NaN,4.5,NaN,Wrocław
9,Michał,23.0,4.0,NaN,4.5,Poznań

In [58]:
df_student["ocena_matematyka"] = df_student["ocena_matematyka"] .fillna(df_student["ocena_matematyka"] .mean())
df_student

,imie,wiek,ocena_matematyka,ocena_fizyka,ocena_informatyka,miasto
0,Anna,20.0,4.50,5.0,4.0,Warszawa
1,Piotr,22.0,4.25,4.5,3.5,Kraków
2,Maria,21.0,5.00,NaN,4.5,Wrocław
3,Jan,21.5,4.00,4.0,NaN,Poznań
4,Katarzyna,23.0,3.50,4.5,5.0,Gdańsk
5,Tomasz,20.0,4.50,NaN,3.5,NaN
6,Magdalena,22.0,5.00,5.0,4.5,Warszawa
7,Paweł,21.5,3.50,4.0,4.0,Kraków
8,Ewa,21.0,4.25,4.5,NaN,Wrocław
9,Michał,23.0,4.00,NaN,4.5,Poznań

In [59]:
df_student["miasto"] = df_student["miasto"].fillna(df_student["miasto"] .mode()[0])
df_student

,imie,wiek,ocena_matematyka,ocena_fizyka,ocena_informatyka,miasto
0,Anna,20.0,4.50,5.0,4.0,Warszawa
1,Piotr,22.0,4.25,4.5,3.5,Kraków
2,Maria,21.0,5.00,NaN,4.5,Wrocław
3,Jan,21.5,4.00,4.0,NaN,Poznań
4,Katarzyna,23.0,3.50,4.5,5.0,Gdańsk
5,Tomasz,20.0,4.50,NaN,3.5,Kraków
6,Magdalena,22.0,5.00,5.0,4.5,Warszawa
7,Paweł,21.5,3.50,4.0,4.0,Kraków
8,Ewa,21.0,4.25,4.5,NaN,Wrocław
9,Michał,23.0,4.00,NaN,4.5,Poznań

## **Obsługa brakujących danych jako stringi**

**Problem**
* Dane często zawierają braki zapisane jako tekst: **"NA", "N/A", "brak", "?", "-", "brak danych"**

* Pandas **nie rozpoznaje** ich automatycznie jako brakujące wartości!

### **Rozwiązanie 1: Wczytywanie z pliku CSV**

```
import pandas as pd

# Definiujemy listę wartości oznaczających brak
braki = ['NA', 'N/A', 'brak', 'brak danych', '?', '-', '']

# Wczytujemy plik z parametrem na_values
df = pd.read_csv('dane.csv', na_values=braki)

```

### **Rozwiązanie 2: Zamiana po wczytaniu**

```
# Zamieniamy wybrane stringi na NaN
df.replace(['NA', 'N/A', 'brak', 'brak danych', '?', '-'], np.nan, inplace=True)

# LUB dla konkretnej kolumny
df['kolumna'] = df['kolumna'].replace('brak', np.nan)
```

# **Zadanie**:

**Dane**: Plik *nieruchomosci.csv* - 45 ofert sprzedaży mieszkań

**Polecenie**

* Wczytaj dane i przeanalizuj problem brakujących wartości

* Zdecyduj, jak poradzić sobie z brakami w poszczególnych kolumnach

* Uzasadnij swoje wybory i zaimplementuj rozwiązanie

**Do przemyślenia**

* Jakie typy zmiennych masz w danych?
* Czy wszystkie braki powinny być obsłużone tak samo?
* Jakie konsekwencje niesie każda metoda?
* Jak to wpływa na eksploracyjną analizę danych?

In [60]:
import pandas as pd
import numpy as np

In [61]:
BRAKI_TEKSTOWE = ['NA', 'N/A', 'brak', 'brak danych', '?', '-', '']

df = pd.read_csv('nieruchomosci.csv', na_values=BRAKI_TEKSTOWE)

print("Podgląd danych:")
print(df.head(10))

Podgląd danych:
   id    miasto     dzielnica  powierzchnia  liczba_pokoi  rok_budowy  pietro  \
0   1  Warszawa       Mokotów          65.0             3      2015.0     4.0
1   2    Kraków     Krowodrza          48.0             2         NaN     2.0
2   3   Wrocław        Krzyki          72.0             3      2010.0     NaN
3   4    Poznań      Grunwald          55.0             2      2018.0     3.0
4   5    Gdańsk      Wrzeszcz          80.0             4      1998.0     1.0
5   6  Warszawa   Śródmieście           NaN             2      2020.0     7.0
6   7    Kraków      Podgórze          60.0             3      2005.0     0.0
7   8   Wrocław  Stare Miasto          45.0             1      2019.0     5.0
8   9    Poznań        Jeżyce          70.0             3         NaN     2.0
9  10    Gdańsk         Oliwa          90.0             4      2001.0     1.0

   liczba_pieter parking balkon          stan  cena_m2  cena_total
0             10     Tak    Tak         Dobry    12500      812500
1              5     Nie    Tak            很好    10200      489600
2              4     Tak    Nie         Dobry     9800      705600
3              8     Tak    Tak  Bardzo dobry    11000      605000
4              3     NaN    Tak    Do remontu     8500      680000
5             12     Tak    Tak  Bardzo dobry    15000     1200000
6              6     Tak    Nie         Dobry     9500      570000
7              9     Nie    Tak  Bardzo dobry    11500      517500
8              4     Tak    Tak         Dobry    10500      735000
9              2     Tak    Tak         Dobry     9000      810000

In [62]:
print("pietro:", sorted(df['pietro'].dropna().unique()))
print("cena_m2:", sorted(df['cena_m2'].dropna().unique()))
print("powierzchnia:", sorted(df['powierzchnia'].dropna().unique()))
print("stan:", df['stan'].unique())

pietro: [np.float64(-999.0), np.float64(0.0), np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0)]
cena_m2: [np.int64(-999), np.int64(-1), np.int64(8200), np.int64(8400), np.int64(8500), np.int64(8600), np.int64(8700), np.int64(8800), np.int64(8900), np.int64(9000), np.int64(9200), np.int64(9300), np.int64(9400), np.int64(9500), np.int64(9600), np.int64(9700), np.int64(9800), np.int64(10000), np.int64(10200), np.int64(10500), np.int64(10800), np.int64(11000), np.int64(11200), np.int64(11500), np.int64(11800), np.int64(12000), np.int64(12500), np.int64(12800), np.int64(13000), np.int64(14000), np.int64(15000)]
powierzchnia: [np.float64(0.0), np.float64(42.0), np.float64(45.0), np.float64(46.0), np.float64(48.0), np.float64(50.0), np.float64(51.0), np.float64(52.0), np.float64(54.0), np.float64(55.0), np.float64(56.0), np.float64(58.0), np.float64(60.0), np.float64(62.0), np.float64(64.0), np.float64(65.0), np.float64(66.0), np.float64(68.0), np.float64(69.0), np.float64(70.0), np.float64(72.0), np.float64(75.0), np.float64(76.0), np.float64(78.0), np.float64(80.0), np.float64(82.0), np.float64(85.0), np.float64(88.0), np.float64(90.0), np.float64(95.0)]
stan: ['Dobry' '很好' 'Bardzo dobry' 'Do remontu']

In [63]:
df['pietro'] = df['pietro'].replace(-999, np.nan)
df['cena_m2'] = df['cena_m2'].replace([-1, -999], np.nan)
df['powierzchnia'] = df['powierzchnia'].replace(0, np.nan)

# poprawiamy
df['stan'] = df['stan'].replace('很好', 'Bardzo dobry')

In [64]:
print("Liczba brakujących wartości w każdej kolumnie:")
print(df.isna().sum())

print("\nProcent brakujących wartości:")
print((df.isna().sum() / len(df) * 100).round(1))

print("\nCałkowita liczba braków:", df.isna().sum().sum())

Liczba brakujących wartości w każdej kolumnie:
id               0
miasto           0
dzielnica        0
powierzchnia     9
liczba_pokoi     0
rok_budowy       7
pietro           3
liczba_pieter    0
parking          5
balkon           3
stan             0
cena_m2          2
cena_total       0
dtype: int64

Procent brakujących wartości:
id                0.0
miasto            0.0
dzielnica         0.0
powierzchnia     20.0
liczba_pokoi      0.0
rok_budowy       15.6
pietro            6.7
liczba_pieter     0.0
parking          11.1
balkon            6.7
stan              0.0
cena_m2           4.4
cena_total        0.0
dtype: float64

Całkowita liczba braków: 29

In [65]:
df['powierzchnia'] = df['powierzchnia'].fillna(df['powierzchnia'].median())
print(f"powierzchnia — mediana użyta do uzupełnienia: {df['powierzchnia'].median():.1f} m²")

mediana_roku = df['rok_budowy'].median()
df['rok_budowy'] = df['rok_budowy'].fillna(mediana_roku).astype(int)
print(f"rok_budowy — mediana użyta do uzupełnienia: {int(mediana_roku)}")

df['pietro'] = df['pietro'].fillna(df['pietro'].median()).astype(int)
print(f"pietro — mediana: {df['pietro'].median():.0f}")

mask_brak_ceny = df['cena_m2'].isna()
df.loc[mask_brak_ceny, 'cena_m2'] = (
    df.loc[mask_brak_ceny, 'cena_total'] / df.loc[mask_brak_ceny, 'powierzchnia']
).round(0).astype(int)
print("\ncena_m2 uzupełniona wyliczeniem z cena_total / powierzchnia.")

dominanta_parking = df['parking'].mode()[0]
df['parking'] = df['parking'].fillna(dominanta_parking)
print(f"parking — dominanta: '{dominanta_parking}'")

dominanta_balkon = df['balkon'].mode()[0]
df['balkon'] = df['balkon'].fillna(dominanta_balkon)
print(f"balkon — dominanta: '{dominanta_balkon}'")

powierzchnia — mediana użyta do uzupełnienia: 63.0 m²
rok_budowy — mediana użyta do uzupełnienia: 2011
pietro — mediana: 3

cena_m2 uzupełniona wyliczeniem z cena_total / powierzchnia.
parking — dominanta: 'Tak'
balkon — dominanta: 'Tak'

In [66]:
print("Czy zostały jakieś braki?")
print(df.isna().sum())

print("\nDataFrame po uzupełnieniu:")
print(df)

Czy zostały jakieś braki?
id               0
miasto           0
dzielnica        0
powierzchnia     0
liczba_pokoi     0
rok_budowy       0
pietro           0
liczba_pieter    0
parking          0
balkon           0
stan             0
cena_m2          0
cena_total       0
dtype: int64

DataFrame po uzupełnieniu:
    id    miasto      dzielnica  powierzchnia  liczba_pokoi  rok_budowy  \
0    1  Warszawa        Mokotów          65.0             3        2015
1    2    Kraków      Krowodrza          48.0             2        2011
2    3   Wrocław         Krzyki          72.0             3        2010
3    4    Poznań       Grunwald          55.0             2        2018
4    5    Gdańsk       Wrzeszcz          80.0             4        1998
5    6  Warszawa    Śródmieście          63.0             2        2020
6    7    Kraków       Podgórze          60.0             3        2005
7    8   Wrocław   Stare Miasto          45.0             1        2019
8    9    Poznań         Jeżyce          70.0             3        2011
9   10    Gdańsk          Oliwa          90.0             4        2001
10  11  Warszawa       Żoliborz          58.0             2        2016
11  12    Kraków      Kazimierz          52.0             2        1995
12  13   Wrocław      Psie Pole          68.0             3        2012
13  14    Poznań         Rataje          63.0             2        2017
14  15    Gdańsk        Siedlce          75.0             3        2011
15  16  Warszawa          Praga          62.0             3        2014
16  17    Kraków      Nowa Huta          50.0             2        2008
17  18   Wrocław      Fabryczna          63.0             4        2011
18  19    Poznań          Wilda          66.0             3        1999
19  20    Gdańsk      Przymorze          85.0             4        2003
20  21  Warszawa         Ochota          54.0             2        2011
21  22    Kraków      Bronowice          63.0             3        2013
22  23   Wrocław         Krzyki          70.0             3        2009
23  24    Poznań        Centrum          48.0             1        2021
24  25    Gdańsk    Śródmieście          95.0             5        1997
25  26  Warszawa        Ursynów          60.0             2        2015
26  27    Kraków        Dębniki          56.0             2        2011
27  28   Wrocław   Stare Miasto          42.0             1        2020
28  29    Poznań       Grunwald          63.0             3        2007
29  30    Gdańsk          Zaspa          78.0             3        2002
30  31  Warszawa        Wilanów          88.0             4        2018
31  32    Kraków     Łagiewniki          63.0             2        2016
32  33   Wrocław       Biskupin          64.0             3        2011
33  34    Poznań         Sołacz          72.0             3        1996
34  35    Gdańsk          Chełm          63.0             4        2014
35  36  Warszawa        Bielany          58.0             2        2011
36  37    Kraków         Ruczaj          51.0             2        2019
37  38   Wrocław            Gaj          69.0             3        2006
38  39    Poznań         Główna          46.0             1        2022
39  40    Gdańsk         Morena          82.0             4        2000
40  41  Warszawa       Targówek          62.0             3        2013
41  42    Kraków  Mistrzejowice          63.0             2        2017
42  43   Wrocław          Ołbin          55.0             2        2011
43  44    Poznań       Piątkowo          63.0             3        2010
44  45    Gdańsk      Suchanino          76.0             3        2004

    pietro  liczba_pieter parking balkon          stan  cena_m2  cena_total
0        4             10     Tak    Tak         Dobry  12500.0      812500
1        2              5     Nie    Tak  Bardzo dobry  10200.0      489600
2        3              4     Tak    Nie         Dobry   9800.0      705600
3        3              8     Tak    Tak  Bardzo dobry  11000.0      605000
4        1              3     Tak    Tak    Do remontu   8500.0      680000
5        7             12     Tak    Tak  Bardzo dobry  15000.0     1200000
6        0              6     Tak    Nie         Dobry   9500.0      570000
7        5              9     Nie    Tak  Bardzo dobry  11500.0      517500
8        2              4     Tak    Tak         Dobry  10500.0      735000
9        1              2     Tak    Tak         Dobry   9000.0      810000
10       3              7     Tak    Tak         Dobry  13000.0      754000
11       3              4     Nie    Tak    Do remontu   9000.0      468000
12       4             10     Tak    Tak         Dobry   8800.0      598400
13       6             11     Tak    Tak  Bardzo dobry  10800.0      648000
14       2              5     Tak    Tak         Dobry   8700.0      652500
15       3              8     Tak    Nie         Dobry  11500.0      713000
16       1              4     Tak    Tak         Dobry   8500.0      425000
17       0              3     Tak    Tak         Dobry   9200.0      644000
18       4              5     Nie    Tak    Do remontu   9000.0      594000
19       2              6     Tak    Tak         Dobry   8900.0      756500
20       5              9     Tak    Tak  Bardzo dobry  12800.0      691200
21       2              7     Tak    Nie         Dobry   9800.0      588000
22       3              8     Tak    Tak         Dobry   9300.0      651000
23       8             15     Tak    Tak  Bardzo dobry  12500.0      600000
24       1              3     Tak    Tak    Do remontu   8200.0      779000
25       4             11     Tak    Tak         Dobry  11800.0      708000
26       1              4     Tak    Tak         Dobry   9600.0      537600
27       6             10     Nie    Tak  Bardzo dobry  12000.0      504000
28       2              5     Tak    Tak         Dobry  10200.0      612000
29       3              9     Tak    Nie         Dobry   8400.0      655200
30       3              6     Tak    Tak  Bardzo dobry  14000.0     1232000
31       4              8     Tak    Tak         Dobry   9400.0      564000
32       1              4     Tak    Tak         Dobry   9700.0      620800
33       0              2     Tak    Tak    Do remontu   9800.0      705600
34       2              7     Tak    Tak         Dobry   8800.0      704000
35       5             10     Tak    Nie         Dobry  11200.0      649600
36       3              9     Tak    Tak  Bardzo dobry  10500.0      535500
37       4              5     Nie    Tak         Dobry   8900.0      614100
38       7             12     Tak    Tak  Bardzo dobry  12500.0      575000
39       1              4     Tak    Tak         Dobry   8895.0      729400
40       2              6     Tak    Tak         Dobry  10500.0      651000
41       6             11     Tak    Tak  Bardzo dobry   9200.0      552000
42       3              7     Tak    Nie         Dobry  10000.0      550000
43       1              5     Tak    Tak         Dobry   9500.0      617500
44       2              8     Tak    Tak         Dobry   8600.0      653600